version: '3.4'

services:
  leavetastic.server:
    image: ${DOCKER_REGISTRY-}leavetasticserver
    build:
        context: .
        dockerfile: Server/Dockerfile
        
  leavetastic.database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"
    volumes:
        - leavetastic-datavolume:/var/lib/mysql  

volumes:
  leavetastic-datavolume: